default: &default
  adapter: <%= ENV['REDIS_URL'] ? 'redis' : 'async' %>
  url: <%= ENV['REDIS_URL'] == 'default' ? 'redis://localhost:6379/1' : ENV['REDIS_URL'] %>

development:
  <<: *default
  channel_prefix: sampleapp_development

test:
  <<: *default
  channel_prefix: sampleapp_test

production:
  <<: *default
  channel_prefix: sampleapp_production
