require 'shellwords'
module ArSync
  class TypesGenerator < ::Rails::Generators::Base
    argument :output_dir, type: :string, desc: "output directory"
    def generate_typescript_files
      dir = ::Rails.root.join output_dir
      comment = "// generated by: rails generate ar_sync:types #{Shellwords.escape output_dir}\n\n"
      ArSync::TypeScript.generate_typed_files SyncApiController, dir: dir, comment: comment
    end
  end
end
